version: "3.3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: SparkybitTest.Api/Dockerfile
    ports:
      - 5001:80
    depends_on: [rabbitmq, mongoDb]
    networks:
      - docker_network

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: SparkybitTest.Consumer/Dockerfile
    depends_on: [rabbitmq, mongoDb, api]
    networks:
      - docker_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - docker_network

  mongoDb:
    image: mongo:5.0
    container_name: mongoDb
    hostname: mongoDb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge